Fix macOS compilation for std::shared_mutex (#370)
## Changes
* Fixes failing compilation on Mac introduced in #364.
* The minimum macOS target is now 10.12 (the previous ones don't support `std::shared_mutex`).

## Review Comments
* I'm aware you might not have macOS, but I don't know where to find a reviewer who does.

## Examples
* Before:
```
➜  SetReplace git:(master) ./build.wls  

CreateLibrary::cmperr: Compile error:
  /Users/maxitg/Development/SetReplace/libSetReplace/Match.cpp:165:16: error:
  'shared_mutex' is unavailable: introduced in macOS 10.12

buildLibSetReplace::fail: Compilation failed.
  Paclet will be created without low level implementation.
Build failed.
```
* After:
```
➜  SetReplace git:(fixMacSharedMutex) ./build.wls 
Build done.
```

<!-- Reviewable:start -->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/370)
<!-- Reviewable:end -->