Linter pre-push hook (#539)
## Changes
* Closes #521.
* Implements a pre-push git hook that runs `./lint.sh` so that the linting issues can be fixed quickly before going to GitHub and CI.
* The hook can be installed by running `scripts/install_git_hooks.sh`.
* Adds a message to `./lint.sh` advising how to fix formatting errors.
* If `./lint.sh` fails on CI, it will now print a message advising to install the git hook.

## Comments
* Note that the hooks live in the `.git/hooks` directory which is not version controlled. Each user has to install them manually. I assume this is done for security reasons so that users don't run the code they don't expect to run.

## Examples
* First, install the hook:
  ```sh
  > scripts/install_git_hooks.sh
  Symlinking /Users/maxitg/git/SetReplace/scripts/git_hooks/pre-push to
    /Users/maxitg/git/SetReplace/.git/hooks/pre-push
  ```
* Next, introduce a formatting/linting issue.
* Now, try to `commit` and `push`:
  ```sh
  > git add .
  > git commit -m "Linting issue."
  [linterHook d331a39] Linting issue.
  1 file changed, 1 insertion(+), 1 deletion(-)
  > git push -u origin linterHook
  --- libSetReplace/Set.cpp
  +++ formatted
  @@ -32 +32 @@
  -    std::unordered_map<Atom, int64_t> atomDegrees_;
  +  std::unordered_map<Atom, int64_t> atomDegrees_;
  
  Found formatting errors. Run ./lint.sh -i to automatically fix by applying the printed patch.
  Linter errors need to be fixed before pushing.
  error: failed to push some refs to 'git@github.com:maxitg/SetReplace.git'
  ```
* As you can see, the linter refuses to push the change due to the linting issue.